build:
  docker:
    - image: circleci/openjdk:8-jdk
  working_directory: ~/repo
  environment:
    - JVM_OPTS: -Xmx3200m
    - TERM: dumb
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
    - run: gradle dependencies
    - store_test_results:
        path: src/test/java/
    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
-run: sudo apt install -y mysql-client
workflows:
  version: 2
  workflow:
    jobs:
      - build{{ checksum "pom.xml" }}